# Generated by Django 4.2.10 on 2025-06-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(choices=[('Mount Pleasant', 'Mount Pleasant'), ('Avondale', 'Avondale'), ('Borrowdale', 'Borrowdale'), ('Highfield', 'Highfield'), ('Eastlea', 'Eastlea'), ('Hatcliffe', 'Hatcliffe'), ('Ruwa', 'Ruwa'), ('Epworth', 'Epworth'), ('Glen Lorne', 'Glen Lorne'), ('Chishawasha', 'Chishawasha')], max_length=32)),
                ('precipitation', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('cloudcover', models.FloatField(blank=True, null=True)),
                ('tempmin', models.FloatField(blank=True, null=True)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('dew', models.FloatField(blank=True, null=True)),
                ('windspeed', models.FloatField(blank=True, null=True)),
                ('winddir', models.FloatField(blank=True, null=True)),
                ('sealevelpressure', models.FloatField(blank=True, null=True)),
                ('precipcover', models.FloatField(blank=True, null=True)),
                ('rain', models.BooleanField()),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
